app/interface/web/__init__.py
from flask import Flask

from app.infrastructure.config import app_config


def create_app(config=app_config) -> Flask:
    app = Flask(__name__)
    app.config.from_object(config)

    from app.interface.web.routes import bp as main_bp
    app.register_blueprint(main_bp)

    return app

app/interface/web/routes.py
from flask import Blueprint
from flask import render_template, make_response


bp = Blueprint('main', __name__)


@bp.route('/')
def index():
    return render_template('index.html')

@bp.route('/manifest')
def manifest():
    res = make_response(render_template('manifest.appcache'), 200)
    res.headers["Content-Type"] = "text/cache-manifest"
    return res

app/interface/web/templates/app_template.html
<script type='text/template' id='app_view_template'>
    <div id="navigation-bar">
    </div>
    <div>
        <h3 class="centered">Date : <%= date %> </h3>
        <div class="d-flex justify-content-around align-items-center">
            <label for="date-picker">Date : </label>
            <input id="date-picker" name="date-picker" type="date" class="content-box" value="<%= date %>"/>
            <button class="change-date content-box">Change date</button>
        </div>
        <div id="mealDiv" class="d-flex justify-content-around flex-wrap">
            <div>
                <div class="col"></div>
            </div>
            <div class="centered content-box">
                <div>Calorie : <%= calorieEaten %> / <%= calorieTarget %></div>
                <div>Carb : <%= nbCarb %></div>
                <div>Fat : <%= nbFat %></div>
                <div>Prot : <%= nbProt %></div>
                <canvas id="pieChart" width="300" height="300"></canvas>
            </div>
        </div>
        <div id="todoDiv">
        </div>
        <div id="sleepDiv">
            Sleep div
        </div>
    </div>
</script>

app/interface/web/templates/index.html
<!doctype html>
<html manifest="{{ url_for('main.manifest') }}">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <script src="{{ url_for('static', filename='js/lib/jquery-3.2.1.slim.min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/lib/popper.min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/lib/bootstrap.min.js')}}"></script>

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='Chart.min.css')}}">

    <title>Macro Count</title>
  </head>
  <body>
    <h1 class="centered">Macro Count !</h1>
    <div id="app"></div>

    {% include 'app_template.html' %}
    {% include 'meal_template.html' %}
    {% include 'meal_col_template.html' %}
    {% include 'meal_col_view_simple_template.html' %}
    {% include 'todo_view_template.html' %}
    {% include 'navbar_template.html' %}
    {% include 'todo_controller_template.html' %}


    <script src="{{ url_for('static', filename='js/lib/jquery-3.5.1.min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/lib/underscore-min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/lib/backbone-min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/lib/backbone-localstorage.js')}}"></script>
    <script src="{{ url_for('static', filename='js/lib/Chart.min.js')}}"></script>


    <script src="{{ url_for('static', filename='js/module/app/model/Meal.js')}}"></script>
    <script src="{{ url_for('static', filename='js/module/app/model/MealCol.js')}}"></script>

    <script src="{{ url_for('static', filename='js/module/app/todo/Todo.js')}}"></script>
    <script src="{{ url_for('static', filename='js/module/app/todo/TodoCol.js')}}"></script>
    <script src="{{ url_for('static', filename='js/module/app/todo/TodoView.js')}}"></script>
    <script src="{{ url_for('static', filename='js/module/app/todo/TodoColView.js')}}"></script>
    <script src="{{ url_for('static', filename='js/module/app/todo/TodoController.js')}}"></script>
    <script src="{{ url_for('static', filename='js/module/app/model/App.js')}}"></script>

    <script src="{{ url_for('static', filename='js/module/app/view/Navbar.js')}}"></script>
    <script src="{{ url_for('static', filename='js/module/app/view/MealView.js')}}"></script>
    <script src="{{ url_for('static', filename='js/module/app/view/MealCOlView.js')}}"></script>
    <script src="{{ url_for('static', filename='js/module/app/view/MealColViewSimple.js')}}"></script>
    <script src="{{ url_for('static', filename='js/module/app/view/AppView.js')}}"></script>



    <script src="{{ url_for('static', filename='js/module/app.js')}}"></script>
  </body>
</html>

app/interface/web/templates/meal_col_template.html
<script type='text/template' id='meal_col_view_template'>
    <div class="new_one box">Create new meal</div>
    <div class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Add new meal !</h5>
                    <button type="button" class="close close_modal" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body d-flex">
                    <div>
                        <label for="name">Meal</label>
                        <label for="fat">Fat</label>
                        <label for="prot">Prot</label>
                        <label for="carb">Carb</label>
                    </div>
                    <div>
                        <input id="name" name="name"/>
                        <input id="fat" name="fat" type="number"/>
                        <input id="prot" name="prot" type="number"/>
                        <input id="carb" name="carb" type="number"/>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="box show_suggestion">From suggestion</button>
                    <button type="button" class="box add_meal_by_modal">Add new meal</button>
                </div>
                <div class="modal-after-footer" style="display: none;overflow: scroll; height:200px;">
                </div>
            </div>
        </div>
    </div>
</script>

app/interface/web/templates/meal_col_view_simple_template.html
<script type='text/template' id='meal_col_view_simple_template'></script>

app/interface/web/templates/meal_template.html
<script type='text/template' id='meal_view_template'>
    <div class="centered content-box">
        <div class="centered">
            <div><%= name %></div>
        </div>
        <div>
            <div>Fat : <%= fat %></div>
            <div>Prot : <%= prot %></div>
            <div>Carb : <%= carb %></div>
            <div>Eaten : <%= eaten %></div>
        </div>
        <div class="delete delete-box">Delete</div>
    </div>
    <hr/>
</script>

app/interface/web/templates/navbar_template.html
<script type='text/template' id='navbar_template'>
    <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link meal" href="#">Meal <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link todo" href="#">Todo</a>
            </li>
            <li class="nav-item">
                <a class="nav-link sleep" href="#">Sleep</a>
            </li>
        <!--
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            -->
            <!--
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item meal" href="#">Meal</a>
                    <a class="dropdown-item todo" href="#">Todo</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item sleep" href="#">Sleep</a>
                </div>
                -->
            <!--
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
                -->
            </li>
            <!--
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
            -->
        </ul>
    </div>
    </nav>
</script>

app/interface/web/templates/todo_controller_template.html
<script type='text/template' id='todo_controller_template'>
    <h3>Todo View</h3>
    <div class="d-flex justify-content-around">
        <input class="item"/>
        <input class="number"/>
        <button class="new_one">Add one</button>
    </div>
    <div class="d-flex justify-content-around">
        <div id="suggestionTodo">
            <h3>Suggestion</h3>
        </div>
        <div id="todoOfTheDay">
            <h3>Of the day</h3>
        </div>
    </div>
</script>

app/interface/web/templates/todo_view_template.html
<script type='text/template' id='todo_view_template'>
    <div class="centered content-box">
        <div>
            <%= item %>
            <%= number %>
        </div>
        <div class="delete delete-box">Delete</div>
    </div>
</script>